export const GET_STARTED = 'GET_STARTED'
export const OFF_SCRIPT = 'OFF_SCRIPT'
export const QUICK_REPLY_DEMO = 'QUICK_REPLY_DEMO'
export const POSTBACK_DEMO = 'POSTBACK_DEMO'
export const GREETING = 'GREETING'
export const QUESTION = 'QUESTION'
export const CLOSING = 'CLOSING'
